// src/app/layout.tsx
import type { Metadata } from "next";
import { Cousine } from "next/font/google";
import "./globals.css"; // Убедитесь, что Tailwind CSS подключен здесь
import Link from "next/link";
import Footer from "@/components/Footer";
import Header from "@/components/Header";

const inter = Cousine({ subsets: ["latin"], weight: '400' });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`flex flex-col min-h-screen ${inter.className}`}>
        <Header />
        <main className="flex-grow p-4">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
